import { ClientProviders } from "@/contexts/ClientProviders";
import { ServerProviders } from "@/contexts/ServerProviders";
import type { Metadata } from "next";
import { Nunito } from "next/font/google";
import "./globals.css";
import { NoScript } from "./no-script";
import "./styles.css";

const nunito = Nunito({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Weather Now",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body className={nunito.className}>
        <ServerProviders>
          <ClientProviders>
            <NoScript />
            {children}
          </ClientProviders>
        </ServerProviders>
      </body>
    </html>
  );
}
